### ISSUE TITLE
Tattoo on the island

### ISSUE THREAD

**Issue by LenoraRose** [AirynS/DSV-Alex-Evelyn-George#1]
When Alex goes to Ginger island, his portrait and sprite both disappear. Entirely. However, his tattoo is there, I'm guessing because it's on a different visual layer? So I click on the tattoo (or where his sprite should be in relation to it, and I get his dialogue, but I can only find him by the little black splotch on the main screen. Help?

**Comment by AirynS** [comment]
Aha, the beach tattoo code block is missing the overlay line of code - I'll get a fix out soon. Thanks for the report!
